// autogenerated from gen/RISCV64.rules: do not edit!
// generated with: cd gen; go run *.go

package ssa

import "math"

var _ = math.MinInt8 // in case not otherwise used
func rewriteValueRISCV64(v *Value) bool {
	switch v.Op {
	case OpAdd64:
		return rewriteValueRISCV64_OpAdd64(v)
	case OpNilCheck:
		return rewriteValueRISCV64_OpNilCheck(v)
	}
	return false
}
func rewriteValueRISCV64_OpAdd64(v *Value) bool {
	b := v.Block
	_ = b
	// match: (Add64 x y)
	// cond:
	// result: (ADD x y)
	for {
		x := v.Args[0]
		y := v.Args[1]
		v.reset(OpRISCV64ADD)
		v.AddArg(x)
		v.AddArg(y)
		return true
	}
	return false
}
func rewriteValueRISCV64_OpNilCheck(v *Value) bool {
	b := v.Block
	_ = b
	// match: (NilCheck ptr mem)
	// cond:
	// result: (ADD ptr mem)
	for {
		ptr := v.Args[0]
		mem := v.Args[1]
		v.reset(OpRISCV64ADD)
		v.AddArg(ptr)
		v.AddArg(mem)
		return true
	}
	return false
}
func rewriteBlockRISCV64(b *Block) bool {
	switch b.Kind {
	}
	return false
}
